name: Build And Test

on:
  push:
    branches: [ master ]
    tags: [ debug ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: make test
